### ISSUE TITLE
peinjector control won't start

### ISSUE THREAD

**Issue by wirehack7** [JonDoNym/peinjector#1]
I installed it on Debian Wheezy, when I want to start peinjector-control I get this error:

```
Traceback (most recent call last):
  File "./peinjector_control.py", line 101, in <module>
    run_https_server(cert=args.cert, ip=args.ip, port=args.port, usessl=args.ssl)
  File "./peinjector_control.py", line 41, in run_https_server
    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)      # create SSLContext with only TLS 1.2
AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_2'
Traceback (most recent call last):
  File "./peinjector_control.py", line 101, in <module>
    run_https_server(cert=args.cert, ip=args.ip, port=args.port, usessl=args.ssl)
  File "./peinjector_control.py", line 41, in run_https_server
    context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)      # create SSLContext with only TLS 1.2
AttributeError: 'module' object has no attribute 'PROTOCOL_TLSv1_2'
```

What to do there?

**Comment by timelf123** [comment]
HTTP/2 sets some very strict standards for the security of the connection, and one of them is that it requires TLSv1.2 for all connections. The Python 2.7 standard library does not provide access to this TLS level in any version earlier than 2.7.9.

I recommend, if possible, either updating your Python 2.7 version or installing Python 3.4. 

`$ apt-get install python3 python3-pip`

Then, use your new python3 executable to try again.

**Comment by JonDoNym** [comment]
That's right, our install script just checked for Python 3.3, fixed.
