### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [JonDoNym/peinjector#3]
Would you like to add more error handling for return values from functions like the following?
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html) ⇒ [pefile_read_file](https://github.com/JonDoNym/peinjector/blob/54ab605e7a0268a204535f63c0a24a26e3360eb2/peinjector/libpefile.c#L355)
- [listen](http://pubs.opengroup.org/onlinepubs/9699919799/functions/listen.html) ⇒ [__peserver_server_handler](https://github.com/JonDoNym/peinjector/blob/54ab605e7a0268a204535f63c0a24a26e3360eb2/peinjector/libpeserver.c#L250)
- [pthread_mutex_lock](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_lock.html) ⇒ [__peprotocol_process_set_section_name](https://github.com/JonDoNym/peinjector/blob/54ab605e7a0268a204535f63c0a24a26e3360eb2/peinjector/libpeprotocol.c#L143)

**Comment by JonDoNym** [comment]
That's right, I'll take a look at this.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html) a bit more.

Are you interested to apply [aspect-oriented software development](http://aspectc.org/)?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](http://en.wikipedia.org/wiki/Aspect_%28computer_programming%29) in your software?
