### ISSUE TITLE
Running with inline scripts

### ISSUE THREAD

**Issue by sweetcharity** [JonDoNym/peinjector#8]
Is it possible to run peinjector-interceptor with mitmproxy's inline scripts http://docs.mitmproxy.org/en/stable/scripting/inlinescripts.html ? 

for ex. this script - https://github.com/mitmproxy/mitmproxy/blob/master/examples/dns_spoofing.py

**Comment by JonDoNym** [comment]
We need the "Streaming-Mode" to manipulate the PE files seamless during download. AFAIK inline script wills wait till the requests/responses are complete, so seamless patching won't work.

None-seamless patching will work definitely, you just have to integrate the Python-Connector (https://github.com/JonDoNym/peinjector/tree/master/peinjector/connectors) in your script. Just insert and patch the PE file as one big block, the patching-engine supports that. 

We currently don't provide an inline script demo or support that kind of usage, but feel free to implement a demo and share the result.
